version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    command: mongod --noauth
    volumes:
      - .:/myApp
    ports:
      - "27017:27017"

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/myApp
    depends_on:
      - mongodb
